### ISSUE TITLE
image

### ISSUE THREAD

**Issue by sheri-thomson** [sheri-thomson/responsive-image-section#2]
@mpelletiervaillant

Hey Mel,

All my screenshots, except the largest one, have gotten through markbot. I can't seem to get my image to the right size. Any suggestions?
TIA :)

**Comment by mpelletiervaillant-zz** [comment]
Hey! 
It's because you have a width of 50% on your .img-flex tag at the large size. So that's making it take 50% of its container. 
You shouldn't really have to touch your .img-flex class at all after the first screen. Taking it off at the large size should fix this.
Hope this helps!

**Comment by sheri-thomson** [comment]
Oh perfect! It simplifies the code too. Thank you :)
